### ISSUE TITLE
Need to add the `--wsgi-disable-file-wrapper` to the uwsgi for the cart

### ISSUE THREAD

**Issue by dmlb2000** [pacifica/pacifica-cookbook#4]
The cart has issues with the wsgi file_wrapper provided with uwsgi, we should add the `--wsgi-disable-file-wrapper` to the command line for the cart frontend.

**Comment by GitBytes** [comment]
@dmlb2000 Do you have a solution being worked up for this yet?

**Comment by dmlb2000** [comment]
This got thrown in with the repository rename commit ... https://github.com/pacifica/pacifica-cookbook/commit/cde6ab92fb3893814e45930af1ee8655f09f4553
